package farm3.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill")
public class Bill implements java.io.Serializable {

	private Integer id;
	private Member member;
	private StatusBill statusBill;
	private TypeBill typeBill;
	private Integer idbill;
	private Date day;
	private Set<ToolBroken> toolBrokens = new HashSet<ToolBroken>(0);

	public Bill() {
	}

	public Bill(Member member, StatusBill statusBill, TypeBill typeBill) {
		this.member = member;
		this.statusBill = statusBill;
		this.typeBill = typeBill;
	}

	public Bill(Member member, StatusBill statusBill, TypeBill typeBill, Integer idbill, Date day,
			Set<ToolBroken> toolBrokens) {
		this.member = member;
		this.statusBill = statusBill;
		this.typeBill = typeBill;
		this.idbill = idbill;
		this.day = day;
		this.toolBrokens = toolBrokens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_bill_id", nullable = false)
	public StatusBill getStatusBill() {
		return this.statusBill;
	}

	public void setStatusBill(StatusBill statusBill) {
		this.statusBill = statusBill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_bill_id", nullable = false)
	public TypeBill getTypeBill() {
		return this.typeBill;
	}

	public void setTypeBill(TypeBill typeBill) {
		this.typeBill = typeBill;
	}

	@Column(name = "idbill")
	public Integer getIdbill() {
		return this.idbill;
	}

	public void setIdbill(Integer idbill) {
		this.idbill = idbill;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "day", length = 19)
	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<ToolBroken> getToolBrokens() {
		return this.toolBrokens;
	}

	public void setToolBrokens(Set<ToolBroken> toolBrokens) {
		this.toolBrokens = toolBrokens;
	}

}
