package farm3.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bucket generated by hbm2java
 */
@Entity
@Table(name = "bucket")
public class Bucket implements java.io.Serializable {

	private Integer id;
	private TypeBucket typeBucket;
	private String code;
	private String number;
	private String name;
	private String brand;
	private String size;
	private Float weightnull;
	private Float weightfull;
	private Float diaPartition;
	private Float diaBody;
	private Float heightBody;
	private Float ratioNitrogen;
	private Integer periodNitrogen;
	private String goblet;
	private Float diaCanister;
	private Float heightCanister;
	private Integer quantityCanister;
	private Float containPerC;
	private String dayInN;
	private String dayExpN;
	private String dayImport;
	private String importBucket;
	private String place;
	private int statusalert;
	private Set<Semen> semens = new HashSet<Semen>(0);

	public Bucket() {
	}

	public Bucket(int statusalert) {
		this.statusalert = statusalert;
	}

	public Bucket(TypeBucket typeBucket, String code, String number, String name, String brand, String size,
			Float weightnull, Float weightfull, Float diaPartition, Float diaBody, Float heightBody,
			Float ratioNitrogen, Integer periodNitrogen, String goblet, Float diaCanister, Float heightCanister,
			Integer quantityCanister, Float containPerC, String dayInN, String dayExpN, String dayImport, String importBucket,
			String place, int statusalert, Set<Semen> semens) {
		this.typeBucket = typeBucket;
		this.code = code;
		this.number = number;
		this.name = name;
		this.brand = brand;
		this.size = size;
		this.weightnull = weightnull;
		this.weightfull = weightfull;
		this.diaPartition = diaPartition;
		this.diaBody = diaBody;
		this.heightBody = heightBody;
		this.ratioNitrogen = ratioNitrogen;
		this.periodNitrogen = periodNitrogen;
		this.goblet = goblet;
		this.diaCanister = diaCanister;
		this.heightCanister = heightCanister;
		this.quantityCanister = quantityCanister;
		this.containPerC = containPerC;
		this.dayInN = dayInN;
		this.dayExpN = dayExpN;
		this.dayImport = dayImport;
		this.importBucket = importBucket;
		this.place = place;
		this.statusalert = statusalert;
		this.semens = semens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_bucket_id")
	public TypeBucket getTypeBucket() {
		return this.typeBucket;
	}

	public void setTypeBucket(TypeBucket typeBucket) {
		this.typeBucket = typeBucket;
	}

	@Column(name = "code", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "number", length = 50)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "brand", length = 100)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "size", length = 100)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Column(name = "weightnull", precision = 12, scale = 0)
	public Float getWeightnull() {
		return this.weightnull;
	}

	public void setWeightnull(Float weightnull) {
		this.weightnull = weightnull;
	}

	@Column(name = "weightfull", precision = 12, scale = 0)
	public Float getWeightfull() {
		return this.weightfull;
	}

	public void setWeightfull(Float weightfull) {
		this.weightfull = weightfull;
	}

	@Column(name = "dia_partition", precision = 12, scale = 0)
	public Float getDiaPartition() {
		return this.diaPartition;
	}

	public void setDiaPartition(Float diaPartition) {
		this.diaPartition = diaPartition;
	}

	@Column(name = "dia_body", precision = 12, scale = 0)
	public Float getDiaBody() {
		return this.diaBody;
	}

	public void setDiaBody(Float diaBody) {
		this.diaBody = diaBody;
	}

	@Column(name = "height_body", precision = 12, scale = 0)
	public Float getHeightBody() {
		return this.heightBody;
	}

	public void setHeightBody(Float heightBody) {
		this.heightBody = heightBody;
	}

	@Column(name = "ratio_nitrogen", precision = 12, scale = 0)
	public Float getRatioNitrogen() {
		return this.ratioNitrogen;
	}

	public void setRatioNitrogen(Float ratioNitrogen) {
		this.ratioNitrogen = ratioNitrogen;
	}

	@Column(name = "period_nitrogen")
	public Integer getPeriodNitrogen() {
		return this.periodNitrogen;
	}

	public void setPeriodNitrogen(Integer periodNitrogen) {
		this.periodNitrogen = periodNitrogen;
	}

	@Column(name = "goblet", length = 45)
	public String getGoblet() {
		return this.goblet;
	}

	public void setGoblet(String goblet) {
		this.goblet = goblet;
	}

	@Column(name = "dia_canister", precision = 12, scale = 0)
	public Float getDiaCanister() {
		return this.diaCanister;
	}

	public void setDiaCanister(Float diaCanister) {
		this.diaCanister = diaCanister;
	}

	@Column(name = "height_canister", precision = 12, scale = 0)
	public Float getHeightCanister() {
		return this.heightCanister;
	}

	public void setHeightCanister(Float heightCanister) {
		this.heightCanister = heightCanister;
	}

	@Column(name = "quantity_canister")
	public Integer getQuantityCanister() {
		return this.quantityCanister;
	}

	public void setQuantityCanister(Integer quantityCanister) {
		this.quantityCanister = quantityCanister;
	}

	@Column(name = "contain_per_c", precision = 12, scale = 0)
	public Float getContainPerC() {
		return this.containPerC;
	}

	public void setContainPerC(Float containPerC) {
		this.containPerC = containPerC;
	}

	@Column(name = "day_in_n", length = 10)
	public String getDayInN() {
		return this.dayInN;
	}

	public void setDayInN(String dayInN) {
		this.dayInN = dayInN;
	}

	@Column(name = "day_exp_n", length = 10)
	public String getDayExpN() {
		return this.dayExpN;
	}

	public void setDayExpN(String dayExpN) {
		this.dayExpN = dayExpN;
	}

	@Column(name = "day_import", length = 10)
	public String getDayImport() {
		return this.dayImport;
	}

	public void setDayImport(String dayImport) {
		this.dayImport = dayImport;
	}

	@Column(name = "import_bucket", length = 100)
	public String getImportBucket() {
		return this.importBucket;
	}

	public void setImportBucket(String importBucket) {
		this.importBucket = importBucket;
	}

	@Column(name = "place", length = 100)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "statusalert", nullable = false)
	public int getStatusalert() {
		return this.statusalert;
	}

	public void setStatusalert(int statusalert) {
		this.statusalert = statusalert;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bucket")
	public Set<Semen> getSemens() {
		return this.semens;
	}

	public void setSemens(Set<Semen> semens) {
		this.semens = semens;
	}

}
