package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CattleStrain generated by hbm2java
 */
@Entity
@Table(name = "cattle_strain")
public class CattleStrain implements java.io.Serializable {

	private Integer id;
	private Member member;
	private String name;
	private String privateNo;
	private String gene;
	private String sex;
	private String birthday;
	private String color;
	private String pic;
	private String pedigree;
	private String lot;
	private String bidder;
	private Float weight;
	private Float weightBirth;
	private Float weightWean;
	private Float weightYear;
	private Float strainStartPrice;
	private Float strainEndPrice;
	private Float strainPercen;
	private Float strainExcise;
	private String father;
	private String mother;
	private String grandfather;
	private String grandmother;
	private String dadGrandfather;
	private String dadGrandmother;
	private String momGrandfather;
	private String momGrandmother;
	private String grandpa;
	private String gramdma;
	private String momGrandpa;
	private String momGrandma;
	private String dadGrandpa;
	private String dadGrandma;
	private String rateMilk;
	private String description;
	private Integer cattleStatus;
	private String commen;

	public CattleStrain() {
	}

	public CattleStrain(Member member) {
		this.member = member;
	}

	public CattleStrain(Member member, String name, String privateNo, String gene, String sex, String birthday,
			String color, String pic, String pedigree, String lot, String bidder, Float weight, Float weightBirth,
			Float weightWean, Float weightYear, Float strainStartPrice, Float strainEndPrice, Float strainPercen,
			Float strainExcise, String father, String mother, String grandfather, String grandmother,
			String dadGrandfather, String dadGrandmother, String momGrandfather, String momGrandmother, String grandpa,
			String gramdma, String momGrandpa, String momGrandma, String dadGrandpa, String dadGrandma, String rateMilk,
			String description, Integer cattleStatus, String commen) {
		this.member = member;
		this.name = name;
		this.privateNo = privateNo;
		this.gene = gene;
		this.sex = sex;
		this.birthday = birthday;
		this.color = color;
		this.pic = pic;
		this.pedigree = pedigree;
		this.lot = lot;
		this.bidder = bidder;
		this.weight = weight;
		this.weightBirth = weightBirth;
		this.weightWean = weightWean;
		this.weightYear = weightYear;
		this.strainStartPrice = strainStartPrice;
		this.strainEndPrice = strainEndPrice;
		this.strainPercen = strainPercen;
		this.strainExcise = strainExcise;
		this.father = father;
		this.mother = mother;
		this.grandfather = grandfather;
		this.grandmother = grandmother;
		this.dadGrandfather = dadGrandfather;
		this.dadGrandmother = dadGrandmother;
		this.momGrandfather = momGrandfather;
		this.momGrandmother = momGrandmother;
		this.grandpa = grandpa;
		this.gramdma = gramdma;
		this.momGrandpa = momGrandpa;
		this.momGrandma = momGrandma;
		this.dadGrandpa = dadGrandpa;
		this.dadGrandma = dadGrandma;
		this.rateMilk = rateMilk;
		this.description = description;
		this.cattleStatus = cattleStatus;
		this.commen = commen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "private_no", length = 50)
	public String getPrivateNo() {
		return this.privateNo;
	}

	public void setPrivateNo(String privateNo) {
		this.privateNo = privateNo;
	}

	@Column(name = "gene", length = 50)
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	@Column(name = "sex", length = 50)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	
	@Column(name = "birthday", length = 10)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "color", length = 50)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "pic", length = 50)
	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	@Column(name = "pedigree", length = 50)
	public String getPedigree() {
		return this.pedigree;
	}

	public void setPedigree(String pedigree) {
		this.pedigree = pedigree;
	}

	@Column(name = "lot", length = 50)
	public String getLot() {
		return this.lot;
	}

	public void setLot(String lot) {
		this.lot = lot;
	}

	@Column(name = "bidder", length = 100)
	public String getBidder() {
		return this.bidder;
	}

	public void setBidder(String bidder) {
		this.bidder = bidder;
	}

	@Column(name = "weight", precision = 12, scale = 0)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	@Column(name = "weight_birth", precision = 12, scale = 0)
	public Float getWeightBirth() {
		return this.weightBirth;
	}

	public void setWeightBirth(Float weightBirth) {
		this.weightBirth = weightBirth;
	}

	@Column(name = "weight_wean", precision = 12, scale = 0)
	public Float getWeightWean() {
		return this.weightWean;
	}

	public void setWeightWean(Float weightWean) {
		this.weightWean = weightWean;
	}

	@Column(name = "weight_year", precision = 12, scale = 0)
	public Float getWeightYear() {
		return this.weightYear;
	}

	public void setWeightYear(Float weightYear) {
		this.weightYear = weightYear;
	}

	@Column(name = "strain_start_price", precision = 12, scale = 0)
	public Float getStrainStartPrice() {
		return this.strainStartPrice;
	}

	public void setStrainStartPrice(Float strainStartPrice) {
		this.strainStartPrice = strainStartPrice;
	}

	@Column(name = "strain_end_price", precision = 12, scale = 0)
	public Float getStrainEndPrice() {
		return this.strainEndPrice;
	}

	public void setStrainEndPrice(Float strainEndPrice) {
		this.strainEndPrice = strainEndPrice;
	}

	@Column(name = "strain_percen", precision = 12, scale = 0)
	public Float getStrainPercen() {
		return this.strainPercen;
	}

	public void setStrainPercen(Float strainPercen) {
		this.strainPercen = strainPercen;
	}

	@Column(name = "strain_excise", precision = 12, scale = 0)
	public Float getStrainExcise() {
		return this.strainExcise;
	}

	public void setStrainExcise(Float strainExcise) {
		this.strainExcise = strainExcise;
	}

	@Column(name = "father", length = 50)
	public String getFather() {
		return this.father;
	}

	public void setFather(String father) {
		this.father = father;
	}

	@Column(name = "mother", length = 50)
	public String getMother() {
		return this.mother;
	}

	public void setMother(String mother) {
		this.mother = mother;
	}

	@Column(name = "grandfather", length = 50)
	public String getGrandfather() {
		return this.grandfather;
	}

	public void setGrandfather(String grandfather) {
		this.grandfather = grandfather;
	}

	@Column(name = "grandmother", length = 50)
	public String getGrandmother() {
		return this.grandmother;
	}

	public void setGrandmother(String grandmother) {
		this.grandmother = grandmother;
	}

	@Column(name = "dad_grandfather", length = 50)
	public String getDadGrandfather() {
		return this.dadGrandfather;
	}

	public void setDadGrandfather(String dadGrandfather) {
		this.dadGrandfather = dadGrandfather;
	}

	@Column(name = "dad_grandmother", length = 50)
	public String getDadGrandmother() {
		return this.dadGrandmother;
	}

	public void setDadGrandmother(String dadGrandmother) {
		this.dadGrandmother = dadGrandmother;
	}

	@Column(name = "mom_grandfather", length = 50)
	public String getMomGrandfather() {
		return this.momGrandfather;
	}

	public void setMomGrandfather(String momGrandfather) {
		this.momGrandfather = momGrandfather;
	}

	@Column(name = "mom_grandmother", length = 50)
	public String getMomGrandmother() {
		return this.momGrandmother;
	}

	public void setMomGrandmother(String momGrandmother) {
		this.momGrandmother = momGrandmother;
	}

	@Column(name = "grandpa", length = 50)
	public String getGrandpa() {
		return this.grandpa;
	}

	public void setGrandpa(String grandpa) {
		this.grandpa = grandpa;
	}

	@Column(name = "gramdma", length = 50)
	public String getGramdma() {
		return this.gramdma;
	}

	public void setGramdma(String gramdma) {
		this.gramdma = gramdma;
	}

	@Column(name = "mom_grandpa", length = 50)
	public String getMomGrandpa() {
		return this.momGrandpa;
	}

	public void setMomGrandpa(String momGrandpa) {
		this.momGrandpa = momGrandpa;
	}

	@Column(name = "mom_grandma", length = 50)
	public String getMomGrandma() {
		return this.momGrandma;
	}

	public void setMomGrandma(String momGrandma) {
		this.momGrandma = momGrandma;
	}

	@Column(name = "dad_grandpa", length = 50)
	public String getDadGrandpa() {
		return this.dadGrandpa;
	}

	public void setDadGrandpa(String dadGrandpa) {
		this.dadGrandpa = dadGrandpa;
	}

	@Column(name = "dad_grandma", length = 50)
	public String getDadGrandma() {
		return this.dadGrandma;
	}

	public void setDadGrandma(String dadGrandma) {
		this.dadGrandma = dadGrandma;
	}

	@Column(name = "rate_milk", length = 50)
	public String getRateMilk() {
		return this.rateMilk;
	}

	public void setRateMilk(String rateMilk) {
		this.rateMilk = rateMilk;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cattle_status")
	public Integer getCattleStatus() {
		return this.cattleStatus;
	}

	public void setCattleStatus(Integer cattleStatus) {
		this.cattleStatus = cattleStatus;
	}

	@Column(name = "commen", length = 100)
	public String getCommen() {
		return this.commen;
	}

	public void setCommen(String commen) {
		this.commen = commen;
	}

}
