package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CattleFatten generated by hbm2java
 */
@Entity
@Table(name = "cattle_fatten")
public class CattleFatten{

	private Integer id;
	private Member member;
	private Integer quantity;
	private String lot;
	private String gene;
	private float weight;
	private float startPrice;
	private float endPrice;
	private Float totalPercen;
	private Float totalExcise;
	private int cattleStatus;
	private String commen;
	private String pic;
	private String bidder;
	private Set<FattenList> fattenLists = new HashSet<FattenList>(0);

	public CattleFatten() {
	}

	public CattleFatten(Member member, String gene, float weight, float startPrice, float endPrice, int cattleStatus) {
		this.member = member;
		this.gene = gene;
		this.weight = weight;
		this.startPrice = startPrice;
		this.endPrice = endPrice;
		this.cattleStatus = cattleStatus;
	}

	public CattleFatten(Member member, Integer quantity, String lot, String gene, float weight, float startPrice,
			float endPrice, Float totalPercen, Float totalExcise, int cattleStatus, String commen, String pic,
			String bidder, Set<FattenList> fattenLists) {
		this.member = member;
		this.quantity = quantity;
		this.lot = lot;
		this.gene = gene;
		this.weight = weight;
		this.startPrice = startPrice;
		this.endPrice = endPrice;
		this.totalPercen = totalPercen;
		this.totalExcise = totalExcise;
		this.cattleStatus = cattleStatus;
		this.commen = commen;
		this.pic = pic;
		this.bidder = bidder;
		this.fattenLists = fattenLists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "lot")
	public String getLot() {
		return this.lot;
	}

	public void setLot(String lot) {
		this.lot = lot;
	}

	@Column(name = "gene")
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	@Column(name = "weight")
	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	@Column(name = "start_price")
	public float getStartPrice() {
		return this.startPrice;
	}

	public void setStartPrice(float startPrice) {
		this.startPrice = startPrice;
	}

	@Column(name = "end_price")
	public float getEndPrice() {
		return this.endPrice;
	}

	public void setEndPrice(float endPrice) {
		this.endPrice = endPrice;
	}

	@Column(name = "total_percen")
	public Float getTotalPercen() {
		return this.totalPercen;
	}

	public void setTotalPercen(Float totalPercen) {
		this.totalPercen = totalPercen;
	}

	@Column(name = "total_excise")
	public Float getTotalExcise() {
		return this.totalExcise;
	}

	public void setTotalExcise(Float totalExcise) {
		this.totalExcise = totalExcise;
	}

	@Column(name = "cattle_status")
	public int getCattleStatus() {
		return this.cattleStatus;
	}

	public void setCattleStatus(int cattleStatus) {
		this.cattleStatus = cattleStatus;
	}

	@Column(name = "commen")
	public String getCommen() {
		return this.commen;
	}

	public void setCommen(String commen) {
		this.commen = commen;
	}

	@Column(name = "pic")
	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	@Column(name = "bidder")
	public String getBidder() {
		return this.bidder;
	}

	public void setBidder(String bidder) {
		this.bidder = bidder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cattleFatten")
	public Set<FattenList> getFattenLists() {
		return this.fattenLists;
	}

	public void setFattenLists(Set<FattenList> fattenLists) {
		this.fattenLists = fattenLists;
	}

}
