package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CattleYear generated by hbm2java
 */
@Entity
@Table(name = "cattle_year")
public class CattleYear implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private Member member;
	private String date;
	private String weightyear;
	private String performer;

	public CattleYear() {
	}

	public CattleYear(Cattle cattle, Member member, String date, String weightyear, String performer) {
		this.cattle = cattle;
		this.member = member;
		this.date = date;
		this.weightyear = weightyear;
		this.performer = performer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	
	@Column(name = "date", length = 10)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "weightyear", length = 50)
	public String getWeightyear() {
		return this.weightyear;
	}

	public void setWeightyear(String weightyear) {
		this.weightyear = weightyear;
	}

	@Column(name = "performer", length = 50)
	public String getPerformer() {
		return this.performer;
	}

	public void setPerformer(String performer) {
		this.performer = performer;
	}
}
