package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CattleShow generated by hbm2java
 */
@Entity
@Table(name = "cattle_show")
public class CattleShow implements java.io.Serializable {

	private Integer id;
	private Member member;
	private String name;
	private String birthday;
	private String sex;
	private String gene;
	private int cattleStatus;
	private String commen;
	private String father;
	private String mother;
	private String deverloper;
	private String pic;
	private String pedegree;

	public CattleShow() {
	}

	public CattleShow(Member member, int cattleStatus) {
		this.member = member;
		this.cattleStatus = cattleStatus;
	}

	public CattleShow(Member member, String name, String birthday, String sex, String gene, int cattleStatus,
			String commen, String father, String mother, String deverloper, String pic, String pedegree) {
		this.member = member;
		this.name = name;
		this.birthday = birthday;
		this.sex = sex;
		this.gene = gene;
		this.cattleStatus = cattleStatus;
		this.commen = commen;
		this.father = father;
		this.mother = mother;
		this.deverloper = deverloper;
		this.pic = pic;
		this.pedegree = pedegree;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	@Column(name = "birthday", length = 10)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "sex", length = 50)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "gene", length = 50)
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	@Column(name = "cattle_status", nullable = false)
	public int getCattleStatus() {
		return this.cattleStatus;
	}

	public void setCattleStatus(int cattleStatus) {
		this.cattleStatus = cattleStatus;
	}

	@Column(name = "commen", length = 100)
	public String getCommen() {
		return this.commen;
	}

	public void setCommen(String commen) {
		this.commen = commen;
	}

	@Column(name = "father", length = 50)
	public String getFather() {
		return this.father;
	}

	public void setFather(String father) {
		this.father = father;
	}

	@Column(name = "mother", length = 50)
	public String getMother() {
		return this.mother;
	}

	public void setMother(String mother) {
		this.mother = mother;
	}

	@Column(name = "deverloper", length = 50)
	public String getDeverloper() {
		return this.deverloper;
	}

	public void setDeverloper(String deverloper) {
		this.deverloper = deverloper;
	}

	@Column(name = "pic", length = 50)
	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	@Column(name = "pedegree", length = 50)
	public String getPedegree() {
		return this.pedegree;
	}

	public void setPedegree(String pedegree) {
		this.pedegree = pedegree;
	}

}
