package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color")
public class Color implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<Cattle> cattles = new HashSet<Cattle>(0);
	private Set<Semen> semens = new HashSet<Semen>(0);

	public Color() {
	}

	public Color(String value) {
		this.value = value;
	}

	public Color(String value, Set<Cattle> cattles, Set<Semen> semens) {
		this.value = value;
		this.cattles = cattles;
		this.semens = semens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", nullable = false, length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Cattle> getCattles() {
		return this.cattles;
	}

	public void setCattles(Set<Cattle> cattles) {
		this.cattles = cattles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Semen> getSemens() {
		return this.semens;
	}

	public void setSemens(Set<Semen> semens) {
		this.semens = semens;
	}

}
