package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FattenList generated by hbm2java
 */
@Entity
@Table(name = "fatten_list")
public class FattenList implements java.io.Serializable {

	private Integer id;
	private CattleFatten cattleFatten;
	private String name;
	private String birthday;
	private String farm;
	private String color;
	private String sex;
	private Float weight;

	public FattenList() {
	}

	public FattenList(CattleFatten cattleFatten) {
		this.cattleFatten = cattleFatten;
	}

	public FattenList(CattleFatten cattleFatten, String name, String birthday, String farm, String color, String sex,
			Float weight) {
		this.cattleFatten = cattleFatten;
		this.name = name;
		this.birthday = birthday;
		this.farm = farm;
		this.color = color;
		this.sex = sex;
		this.weight = weight;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_fatten_id", nullable = false)
	public CattleFatten getCattleFatten() {
		return this.cattleFatten;
	}

	public void setCattleFatten(CattleFatten cattleFatten) {
		this.cattleFatten = cattleFatten;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	@Column(name = "birthday", length = 10)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "farm", length = 50)
	public String getFarm() {
		return this.farm;
	}

	public void setFarm(String farm) {
		this.farm = farm;
	}

	@Column(name = "color", length = 50)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "sex", length = 50)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "weight", precision = 12, scale = 0)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

}
