package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Festivity generated by hbm2java
 */
@Entity
@Table(name = "festivity")
public class Festivity implements java.io.Serializable {

	private Integer id;
	private Member member;
	private Type type;
	private String title;
	private String gene;
	private String SWork;
	private String EWork;
	private String SData;
	private String EData;
	private String logo;
	private String poster;
	private String details;
	private String location;
	private String referee;
	private Integer newStatus;
	private String cowId;
	private Integer percen;
	private String farmName;
	private String phone;
	private Set<FestivityFattenHistory> festivityFattenHistories = new HashSet<FestivityFattenHistory>(0);
	private Set<Worktogether> worktogethers = new HashSet<Worktogether>(0);
	private Set<FestivityShowHistory> festivityShowHistories = new HashSet<FestivityShowHistory>(0);
	private Set<FestivityStrainHistory> festivityStrainHistories = new HashSet<FestivityStrainHistory>(0);

	public Festivity() {
	}

	public Festivity(Member member, Type type, String title, String gene, String SWork, String EWork, String SData,
			String EData, String logo, String poster, String details, String location, String referee, Integer newStatus,
			String cowId, Integer percen, String farmName, String phone,
			Set<FestivityFattenHistory> festivityFattenHistories, Set<Worktogether> worktogethers,
			Set<FestivityShowHistory> festivityShowHistories, Set<FestivityStrainHistory> festivityStrainHistories) {
		this.member = member;
		this.type = type;
		this.title = title;
		this.gene = gene;
		this.SWork = SWork;
		this.EWork = EWork;
		this.SData = SData;
		this.EData = EData;
		this.logo = logo;
		this.poster = poster;
		this.details = details;
		this.location = location;
		this.referee = referee;
		this.newStatus = newStatus;
		this.cowId = cowId;
		this.percen = percen;
		this.farmName = farmName;
		this.phone = phone;
		this.festivityFattenHistories = festivityFattenHistories;
		this.worktogethers = worktogethers;
		this.festivityShowHistories = festivityShowHistories;
		this.festivityStrainHistories = festivityStrainHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "gene", length = 50)
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	
	@Column(name = "s_work", length = 10)
	public String getSWork() {
		return this.SWork;
	}

	public void setSWork(String SWork) {
		this.SWork = SWork;
	}

	
	@Column(name = "e_work", length = 10)
	public String getEWork() {
		return this.EWork;
	}

	public void setEWork(String EWork) {
		this.EWork = EWork;
	}

	
	@Column(name = "s_data", length = 10)
	public String getSData() {
		return this.SData;
	}

	public void setSData(String SData) {
		this.SData = SData;
	}


	@Column(name = "e_data", length = 10)
	public String getEData() {
		return this.EData;
	}

	public void setEData(String EData) {
		this.EData = EData;
	}

	@Column(name = "logo", length = 50)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "poster", length = 50)
	public String getPoster() {
		return this.poster;
	}

	public void setPoster(String poster) {
		this.poster = poster;
	}

	@Column(name = "details", length = 200)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "location", length = 200)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "referee", length = 50)
	public String getReferee() {
		return this.referee;
	}

	public void setReferee(String referee) {
		this.referee = referee;
	}

	@Column(name = "new_status")
	public Integer getNewStatus() {
		return this.newStatus;
	}

	public void setNewStatus(Integer newStatus) {
		this.newStatus = newStatus;
	}

	@Column(name = "cow_id", length = 50)
	public String getCowId() {
		return this.cowId;
	}

	public void setCowId(String cowId) {
		this.cowId = cowId;
	}

	@Column(name = "percen")
	public Integer getPercen() {
		return this.percen;
	}

	public void setPercen(Integer percen) {
		this.percen = percen;
	}

	@Column(name = "farm_name", length = 50)
	public String getFarmName() {
		return this.farmName;
	}

	public void setFarmName(String farmName) {
		this.farmName = farmName;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "festivity")
	public Set<FestivityFattenHistory> getFestivityFattenHistories() {
		return this.festivityFattenHistories;
	}

	public void setFestivityFattenHistories(Set<FestivityFattenHistory> festivityFattenHistories) {
		this.festivityFattenHistories = festivityFattenHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "festivity")
	public Set<Worktogether> getWorktogethers() {
		return this.worktogethers;
	}

	public void setWorktogethers(Set<Worktogether> worktogethers) {
		this.worktogethers = worktogethers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "festivity")
	public Set<FestivityShowHistory> getFestivityShowHistories() {
		return this.festivityShowHistories;
	}

	public void setFestivityShowHistories(Set<FestivityShowHistory> festivityShowHistories) {
		this.festivityShowHistories = festivityShowHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "festivity")
	public Set<FestivityStrainHistory> getFestivityStrainHistories() {
		return this.festivityStrainHistories;
	}

	public void setFestivityStrainHistories(Set<FestivityStrainHistory> festivityStrainHistories) {
		this.festivityStrainHistories = festivityStrainHistories;
	}

}
