package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.google.gson.annotations.Expose;

/**
 * Medicine generated by hbm2java
 */
@Entity
@Table(name = "medicine")
public class Medicine implements java.io.Serializable {

	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	
	
	
	
	
	@ManyToOne
	@JoinColumn(name = "group_medicine_id")
	private GroupMedicine groupMedicine;
	@ManyToOne
	@JoinColumn(name = "unit_medicine_id")
	@Expose private UnitMedicine unitMedicine;
	@Column(name = "trade_name")
	@Expose private String tradeName;
	@Column(name = "scientific_name")
	@Expose private String scientificName;
	@Column(name = "common_name")
	@Expose private String commonName;
	@Column(name = "qty")
	private Long qty;
	@Column(name = "quantity")
	@Expose private Integer quantity;
	@Column(name = "ingredient")
	private String ingredient;
	@Column(name = "properties")
	private String properties;
	@Column(name = "instruction")
	private String instruction;
	@Column(name = "direction")
	private String direction;
	@Column(name = "contraindicated")
	private String contraindicated;
	@Column(name = "caution")
	private String caution;
	@Column(name = "side_effect")
	private String sideEffect;
	@Column(name = "distance_discontinued")
	@Expose private String distanceDiscontinued;
	@Column(name = "mfg_date")
	private Date mfgDate;
	@Column(name = "exp_date")
	private Date expDate;
	@Column(name = "product_by")
	private String productBy;
	@Column(name = "note")
	private String note;
	@Column(name = "image")
	private String image;
	@Column(name = "barcode")
	private String barcode;
	@Column(name = "place")
	private String place;
	@Column(name = "statusalert")
	private int statusalert;
	@Column(name = "medicine_success")
	private Integer medicineSuccess;
	@Column(name = "medicine_lost")
	private Integer medicineLost;
	
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "medicine")
	@Fetch(value = FetchMode.SUBSELECT)
	private List<MedicineRelease> medicineReleases;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "medicine")
	@Fetch(value = FetchMode.SUBSELECT)
	private List<MedicineHealth> medicineHealth;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "medicine")
	@Fetch(value = FetchMode.SUBSELECT)
	private List<MedicineOrder> medicineOrders ;
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "medicine")
	@Fetch(value = FetchMode.SUBSELECT)
	private List<MedicineImport> medicineImports;
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "medicine")
	@Fetch(value = FetchMode.SUBSELECT)
	private List<TreatmentHistory> treatmentHistories;

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public GroupMedicine getGroupMedicine() {
		return groupMedicine;
	}
	public void setGroupMedicine(GroupMedicine groupMedicine) {
		this.groupMedicine = groupMedicine;
	}
	
	
	
	
	
	public UnitMedicine getUnitMedicine() {
		return unitMedicine;
	}
	public void setUnitMedicine(UnitMedicine unitMedicine) {
		this.unitMedicine = unitMedicine;
	}
	public String getTradeName() {
		return tradeName;
	}
	public void setTradeName(String tradeName) {
		this.tradeName = tradeName;
	}
	public String getScientificName() {
		return scientificName;
	}
	public void setScientificName(String scientificName) {
		this.scientificName = scientificName;
	}
	public String getCommonName() {
		return commonName;
	}
	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}
	public Long getQty() {
		return qty;
	}
	public void setQty(Long qty) {
		this.qty = qty;
	}
	public Integer getQuantity() {
		return quantity;
	}
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public String getIngredient() {
		return ingredient;
	}
	public void setIngredient(String ingredient) {
		this.ingredient = ingredient;
	}
	public String getProperties() {
		return properties;
	}
	public void setProperties(String properties) {
		this.properties = properties;
	}
	public String getInstruction() {
		return instruction;
	}
	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}
	public String getDirection() {
		return direction;
	}
	public void setDirection(String direction) {
		this.direction = direction;
	}
	public String getContraindicated() {
		return contraindicated;
	}
	public void setContraindicated(String contraindicated) {
		this.contraindicated = contraindicated;
	}
	public String getCaution() {
		return caution;
	}
	public void setCaution(String caution) {
		this.caution = caution;
	}
	public String getSideEffect() {
		return sideEffect;
	}
	public void setSideEffect(String sideEffect) {
		this.sideEffect = sideEffect;
	}
	public String getDistanceDiscontinued() {
		return distanceDiscontinued;
	}
	public void setDistanceDiscontinued(String distanceDiscontinued) {
		this.distanceDiscontinued = distanceDiscontinued;
	}
	public Date getMfgDate() {
		return mfgDate;
	}
	public void setMfgDate(Date mfgDate) {
		this.mfgDate = mfgDate;
	}
	public Date getExpDate() {
		return expDate;
	}
	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}
	public String getProductBy() {
		return productBy;
	}
	public void setProductBy(String productBy) {
		this.productBy = productBy;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public String getImage() {
		return image;
	}
	public void setImage(String image) {
		this.image = image;
	}
	public String getBarcode() {
		return barcode;
	}
	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}
	public String getPlace() {
		return place;
	}
	public void setPlace(String place) {
		this.place = place;
	}
	public int getStatusalert() {
		return statusalert;
	}
	public void setStatusalert(int statusalert) {
		this.statusalert = statusalert;
	}
	public Integer getMedicineSuccess() {
		return medicineSuccess;
	}
	public void setMedicineSuccess(Integer medicineSuccess) {
		this.medicineSuccess = medicineSuccess;
	}
	public Integer getMedicineLost() {
		return medicineLost;
	}
	public void setMedicineLost(Integer medicineLost) {
		this.medicineLost = medicineLost;
	}
	
	
	public List<MedicineRelease> getMedicineReleases() {
		return medicineReleases;
	}
	public void setMedicineReleases(List<MedicineRelease> medicineReleases) {
		this.medicineReleases = medicineReleases;
	}
	
	public List<MedicineHealth> getMedicineHealth() {
		return medicineHealth;
	}
	public void setMedicineHealth(List<MedicineHealth> medicineHealth) {
		this.medicineHealth = medicineHealth;
	}
	
	public List<MedicineOrder> getMedicineOrders() {
		return medicineOrders;
	}
	public void setMedicineOrders(List<MedicineOrder> medicineOrders) {
		this.medicineOrders = medicineOrders;
	}
	public List<MedicineImport> getMedicineImports() {
		return medicineImports;
	}
	public void setMedicineImports(List<MedicineImport> medicineImports) {
		this.medicineImports = medicineImports;
	}
	public List<TreatmentHistory> getTreatmentHistories() {
		return treatmentHistories;
	}
	public void setTreatmentHistories(List<TreatmentHistory> treatmentHistories) {
		this.treatmentHistories = treatmentHistories;
	}
	
	
	/*private Integer id;
	private GroupMedicine groupMedicine;
	@Expose private UnitMedicine unitMedicine;
	private String tradeName;
	private String scientificName;
	private String commonName;
	private Long qty;
	@Expose private Integer quantity;
	private String ingredient;
	private String properties;
	private String instruction;
	private String direction;
	private String contraindicated;
	private String caution;
	private String sideEffect;
	private String distanceDiscontinued;
	private Date mfgDate;
	private Date expDate;
	private String productBy;
	private String note;
	private String image;
	private String barcode;
	private String place;
	private int statusalert;
	private Integer medicineSuccess;
	private Integer medicineLost;
	private Set<MedicineRelease> medicineReleases = new HashSet<MedicineRelease>(0);
	private Set<MedicineOrder> medicineOrders = new HashSet<MedicineOrder>(0);
	private Set<MedicineImport> medicineImports = new HashSet<MedicineImport>(0);
	private Set<TreatmentHistory> treatmentHistories = new HashSet<TreatmentHistory>(0);

	public Medicine() {
	}

	public Medicine(int statusalert) {
		this.statusalert = statusalert;
	}

	public Medicine(GroupMedicine groupMedicine, UnitMedicine unitMedicine, String tradeName, String scientificName,
			String commonName, Long qty, Integer quantity, String ingredient, String properties, String instruction,
			String direction, String contraindicated, String caution, String sideEffect, String distanceDiscontinued,
			Date mfgDate, Date expDate, String productBy, String note, String image, String barcode, String place,
			int statusalert, Integer medicineSuccess, Integer medicineLost, Set<MedicineRelease> medicineReleases,
			Set<MedicineOrder> medicineOrders, Set<MedicineImport> medicineImports,
			Set<TreatmentHistory> treatmentHistories) {
		this.groupMedicine = groupMedicine;
		this.unitMedicine = unitMedicine;
		this.tradeName = tradeName;
		this.scientificName = scientificName;
		this.commonName = commonName;
		this.qty = qty;
		this.quantity = quantity;
		this.ingredient = ingredient;
		this.properties = properties;
		this.instruction = instruction;
		this.direction = direction;
		this.contraindicated = contraindicated;
		this.caution = caution;
		this.sideEffect = sideEffect;
		this.distanceDiscontinued = distanceDiscontinued;
		this.mfgDate = mfgDate;
		this.expDate = expDate;
		this.productBy = productBy;
		this.note = note;
		this.image = image;
		this.barcode = barcode;
		this.place = place;
		this.statusalert = statusalert;
		this.medicineSuccess = medicineSuccess;
		this.medicineLost = medicineLost;
		this.medicineReleases = medicineReleases;
		this.medicineOrders = medicineOrders;
		this.medicineImports = medicineImports;
		this.treatmentHistories = treatmentHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_medicine_id")
	public GroupMedicine getGroupMedicine() {
		return this.groupMedicine;
	}

	public void setGroupMedicine(GroupMedicine groupMedicine) {
		this.groupMedicine = groupMedicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unit_medicine_id")
	public UnitMedicine getUnitMedicine() {
		return this.unitMedicine;
	}

	public void setUnitMedicine(UnitMedicine unitMedicine) {
		this.unitMedicine = unitMedicine;
	}

	@Column(name = "trade_name", length = 200)
	public String getTradeName() {
		return this.tradeName;
	}

	public void setTradeName(String tradeName) {
		this.tradeName = tradeName;
	}

	@Column(name = "scientific_name", length = 100)
	public String getScientificName() {
		return this.scientificName;
	}

	public void setScientificName(String scientificName) {
		this.scientificName = scientificName;
	}

	@Column(name = "common_name", length = 100)
	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

	@Column(name = "qty", precision = 10, scale = 0)
	public Long getQty() {
		return this.qty;
	}

	public void setQty(Long qty) {
		this.qty = qty;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "ingredient", length = 1000)
	public String getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(String ingredient) {
		this.ingredient = ingredient;
	}

	@Column(name = "properties", length = 1000)
	public String getProperties() {
		return this.properties;
	}

	public void setProperties(String properties) {
		this.properties = properties;
	}

	@Column(name = "instruction", length = 400)
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	@Column(name = "direction", length = 45)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "contraindicated", length = 400)
	public String getContraindicated() {
		return this.contraindicated;
	}

	public void setContraindicated(String contraindicated) {
		this.contraindicated = contraindicated;
	}

	@Column(name = "caution", length = 45)
	public String getCaution() {
		return this.caution;
	}

	public void setCaution(String caution) {
		this.caution = caution;
	}

	@Column(name = "side_effect", length = 45)
	public String getSideEffect() {
		return this.sideEffect;
	}

	public void setSideEffect(String sideEffect) {
		this.sideEffect = sideEffect;
	}

	@Column(name = "distance_discontinued", length = 100)
	public String getDistanceDiscontinued() {
		return this.distanceDiscontinued;
	}

	public void setDistanceDiscontinued(String distanceDiscontinued) {
		this.distanceDiscontinued = distanceDiscontinued;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mfg_date", length = 10)
	public Date getMfgDate() {
		return this.mfgDate;
	}

	public void setMfgDate(Date mfgDate) {
		this.mfgDate = mfgDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "exp_date", length = 10)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "product_by", length = 45)
	public String getProductBy() {
		return this.productBy;
	}

	public void setProductBy(String productBy) {
		this.productBy = productBy;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "image", length = 100)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "barcode", length = 45)
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	@Column(name = "place", length = 45)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "statusalert", nullable = false)
	public int getStatusalert() {
		return this.statusalert;
	}

	public void setStatusalert(int statusalert) {
		this.statusalert = statusalert;
	}

	@Column(name = "medicine_success")
	public Integer getMedicineSuccess() {
		return this.medicineSuccess;
	}

	public void setMedicineSuccess(Integer medicineSuccess) {
		this.medicineSuccess = medicineSuccess;
	}

	@Column(name = "medicine_lost")
	public Integer getMedicineLost() {
		return this.medicineLost;
	}

	public void setMedicineLost(Integer medicineLost) {
		this.medicineLost = medicineLost;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicine")
	public Set<MedicineRelease> getMedicineReleases() {
		return this.medicineReleases;
	}

	public void setMedicineReleases(Set<MedicineRelease> medicineReleases) {
		this.medicineReleases = medicineReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicine")
	public Set<MedicineOrder> getMedicineOrders() {
		return this.medicineOrders;
	}

	public void setMedicineOrders(Set<MedicineOrder> medicineOrders) {
		this.medicineOrders = medicineOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicine")
	public Set<MedicineImport> getMedicineImports() {
		return this.medicineImports;
	}

	public void setMedicineImports(Set<MedicineImport> medicineImports) {
		this.medicineImports = medicineImports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicine")
	public Set<TreatmentHistory> getTreatmentHistories() {
		return this.treatmentHistories;
	}

	public void setTreatmentHistories(Set<TreatmentHistory> treatmentHistories) {
		this.treatmentHistories = treatmentHistories;
	}*/

}
