package farm3.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member")
public class Member implements java.io.Serializable {

	private Integer id;
	private Privilege privilege;
	private String username;
	private String password;
	private String first;
	private String last;
	private String birthday;
	private String age;
	private String sex;
	private String idCard;
	private String nationlity;
	private String tel;
	private String mobile;
	private String fax;
	private String address;
	private String zipcode;
	private String email;
	private String altEmail;
	private String image;
	private String question;
	private String answer;
	private Set<ToolBorrow> toolBorrows = new HashSet<ToolBorrow>(0);
	private Set<CattleWean> cattleWeans = new HashSet<CattleWean>(0);
	private Set<Breeding> breedings = new HashSet<Breeding>(0);
	private Set<CattleYear> cattleYears = new HashSet<CattleYear>(0);
	private Set<TreatmentHistory> treatmentHistories = new HashSet<TreatmentHistory>(0);
	private Set<CattleStamp> cattleStamps = new HashSet<CattleStamp>(0);
	private Set<ToolBroken> toolBrokens = new HashSet<ToolBroken>(0);
	private Set<Festivity> festivities = new HashSet<Festivity>(0);
	private Set<SemenOrder> semenOrders = new HashSet<SemenOrder>(0);
	private Set<ToolImport> toolImports = new HashSet<ToolImport>(0);
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<HornDetering> hornDeterings = new HashSet<HornDetering>(0);
	private Set<CattleFatten> cattleFattens = new HashSet<CattleFatten>(0);
	private Set<Synchronize> synchronizes = new HashSet<Synchronize>(0);
	private Set<FormulaRecord> formulaRecords = new HashSet<FormulaRecord>(0);
	private Set<SemenImport> semenImports = new HashSet<SemenImport>(0);
	private Set<SemenRelease> semenReleases = new HashSet<SemenRelease>(0);
	private Set<Misscarry> misscarries = new HashSet<Misscarry>(0);
	private Set<RawMaterialRelease> rawMaterialReleases = new HashSet<RawMaterialRelease>(0);
	private Set<CattleShow> cattleShows = new HashSet<CattleShow>(0);
	private Set<MedicineImport> medicineImports = new HashSet<MedicineImport>(0);
	private Set<ToolRelease> toolReleases = new HashSet<ToolRelease>(0);
	private Set<Alert> alerts = new HashSet<Alert>(0);
	private Set<MedicineRelease> medicineReleases = new HashSet<MedicineRelease>(0);
	private Set<RawMaterialImport> rawMaterialImports = new HashSet<RawMaterialImport>(0);
	private Set<CattleStrain> cattleStrains = new HashSet<CattleStrain>(0);
	private Set<RawMaterialOrder> rawMaterialOrders = new HashSet<RawMaterialOrder>(0);
	private Set<ToolOrder> toolOrders = new HashSet<ToolOrder>(0);
	private Set<Disease> diseases = new HashSet<Disease>(0);
	private Set<FormulaRecord2> formulaRecord2s = new HashSet<FormulaRecord2>(0);
	private Set<MedicineOrder> medicineOrders = new HashSet<MedicineOrder>(0);
	private Set<Pregnant> pregnants = new HashSet<Pregnant>(0);

	public Member() {
	}

	public Member(Privilege privilege) {
		this.privilege = privilege;
	}

	public Member(Privilege privilege, String username, String password, String first, String last, String birthday,
			String age, String sex, String idCard, String nationlity, String tel, String mobile, String fax,
			String address, String zipcode, String email, String altEmail, String image, String question, String answer,
			Set<ToolBorrow> toolBorrows, Set<CattleWean> cattleWeans, Set<Breeding> breedings,
			Set<CattleYear> cattleYears, Set<TreatmentHistory> treatmentHistories, Set<CattleStamp> cattleStamps,
			Set<ToolBroken> toolBrokens, Set<Festivity> festivities, Set<SemenOrder> semenOrders,
			Set<ToolImport> toolImports, Set<Bill> bills, Set<HornDetering> hornDeterings,
			Set<CattleFatten> cattleFattens, Set<Synchronize> synchronizes, Set<FormulaRecord> formulaRecords,
			Set<SemenImport> semenImports, Set<SemenRelease> semenReleases, Set<Misscarry> misscarries,
			Set<RawMaterialRelease> rawMaterialReleases, Set<CattleShow> cattleShows,
			Set<MedicineImport> medicineImports, Set<ToolRelease> toolReleases, Set<Alert> alerts,
			Set<MedicineRelease> medicineReleases, Set<RawMaterialImport> rawMaterialImports,
			Set<CattleStrain> cattleStrains, Set<RawMaterialOrder> rawMaterialOrders, Set<ToolOrder> toolOrders,
			Set<Disease> diseases, Set<FormulaRecord2> formulaRecord2s, Set<MedicineOrder> medicineOrders,
			Set<Pregnant> pregnants) {
		this.privilege = privilege;
		this.username = username;
		this.password = password;
		this.first = first;
		this.last = last;
		this.birthday = birthday;
		this.age = age;
		this.sex = sex;
		this.idCard = idCard;
		this.nationlity = nationlity;
		this.tel = tel;
		this.mobile = mobile;
		this.fax = fax;
		this.address = address;
		this.zipcode = zipcode;
		this.email = email;
		this.altEmail = altEmail;
		this.image = image;
		this.question = question;
		this.answer = answer;
		this.toolBorrows = toolBorrows;
		this.cattleWeans = cattleWeans;
		this.breedings = breedings;
		this.cattleYears = cattleYears;
		this.treatmentHistories = treatmentHistories;
		this.cattleStamps = cattleStamps;
		this.toolBrokens = toolBrokens;
		this.festivities = festivities;
		this.semenOrders = semenOrders;
		this.toolImports = toolImports;
		this.bills = bills;
		this.hornDeterings = hornDeterings;
		this.cattleFattens = cattleFattens;
		this.synchronizes = synchronizes;
		this.formulaRecords = formulaRecords;
		this.semenImports = semenImports;
		this.semenReleases = semenReleases;
		this.misscarries = misscarries;
		this.rawMaterialReleases = rawMaterialReleases;
		this.cattleShows = cattleShows;
		this.medicineImports = medicineImports;
		this.toolReleases = toolReleases;
		this.alerts = alerts;
		this.medicineReleases = medicineReleases;
		this.rawMaterialImports = rawMaterialImports;
		this.cattleStrains = cattleStrains;
		this.rawMaterialOrders = rawMaterialOrders;
		this.toolOrders = toolOrders;
		this.diseases = diseases;
		this.formulaRecord2s = formulaRecord2s;
		this.medicineOrders = medicineOrders;
		this.pregnants = pregnants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "privilege_id", nullable = false)
	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first", length = 45)
	public String getFirst() {
		return this.first;
	}

	public void setFirst(String first) {
		this.first = first;
	}

	@Column(name = "last", length = 45)
	public String getLast() {
		return this.last;
	}

	public void setLast(String last) {
		this.last = last;
	}

	
	@Column(name = "birthday", length = 10)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "age", length = 5)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "sex", length = 5)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "id_card", length = 15)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "nationlity", length = 10)
	public String getNationlity() {
		return this.nationlity;
	}

	public void setNationlity(String nationlity) {
		this.nationlity = nationlity;
	}

	@Column(name = "tel", length = 15)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "mobile", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "zipcode", length = 10)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "alt_email", length = 45)
	public String getAltEmail() {
		return this.altEmail;
	}

	public void setAltEmail(String altEmail) {
		this.altEmail = altEmail;
	}

	@Column(name = "image", length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "question", length = 45)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "answer", length = 45)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<ToolBorrow> getToolBorrows() {
		return this.toolBorrows;
	}

	public void setToolBorrows(Set<ToolBorrow> toolBorrows) {
		this.toolBorrows = toolBorrows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<CattleWean> getCattleWeans() {
		return this.cattleWeans;
	}

	public void setCattleWeans(Set<CattleWean> cattleWeans) {
		this.cattleWeans = cattleWeans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Breeding> getBreedings() {
		return this.breedings;
	}

	public void setBreedings(Set<Breeding> breedings) {
		this.breedings = breedings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<CattleYear> getCattleYears() {
		return this.cattleYears;
	}

	public void setCattleYears(Set<CattleYear> cattleYears) {
		this.cattleYears = cattleYears;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<TreatmentHistory> getTreatmentHistories() {
		return this.treatmentHistories;
	}

	public void setTreatmentHistories(Set<TreatmentHistory> treatmentHistories) {
		this.treatmentHistories = treatmentHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<CattleStamp> getCattleStamps() {
		return this.cattleStamps;
	}

	public void setCattleStamps(Set<CattleStamp> cattleStamps) {
		this.cattleStamps = cattleStamps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<ToolBroken> getToolBrokens() {
		return this.toolBrokens;
	}

	public void setToolBrokens(Set<ToolBroken> toolBrokens) {
		this.toolBrokens = toolBrokens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Festivity> getFestivities() {
		return this.festivities;
	}

	public void setFestivities(Set<Festivity> festivities) {
		this.festivities = festivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<SemenOrder> getSemenOrders() {
		return this.semenOrders;
	}

	public void setSemenOrders(Set<SemenOrder> semenOrders) {
		this.semenOrders = semenOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<ToolImport> getToolImports() {
		return this.toolImports;
	}

	public void setToolImports(Set<ToolImport> toolImports) {
		this.toolImports = toolImports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<HornDetering> getHornDeterings() {
		return this.hornDeterings;
	}

	public void setHornDeterings(Set<HornDetering> hornDeterings) {
		this.hornDeterings = hornDeterings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<CattleFatten> getCattleFattens() {
		return this.cattleFattens;
	}

	public void setCattleFattens(Set<CattleFatten> cattleFattens) {
		this.cattleFattens = cattleFattens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Synchronize> getSynchronizes() {
		return this.synchronizes;
	}

	public void setSynchronizes(Set<Synchronize> synchronizes) {
		this.synchronizes = synchronizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<FormulaRecord> getFormulaRecords() {
		return this.formulaRecords;
	}

	public void setFormulaRecords(Set<FormulaRecord> formulaRecords) {
		this.formulaRecords = formulaRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<SemenImport> getSemenImports() {
		return this.semenImports;
	}

	public void setSemenImports(Set<SemenImport> semenImports) {
		this.semenImports = semenImports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<SemenRelease> getSemenReleases() {
		return this.semenReleases;
	}

	public void setSemenReleases(Set<SemenRelease> semenReleases) {
		this.semenReleases = semenReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Misscarry> getMisscarries() {
		return this.misscarries;
	}

	public void setMisscarries(Set<Misscarry> misscarries) {
		this.misscarries = misscarries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<RawMaterialRelease> getRawMaterialReleases() {
		return this.rawMaterialReleases;
	}

	public void setRawMaterialReleases(Set<RawMaterialRelease> rawMaterialReleases) {
		this.rawMaterialReleases = rawMaterialReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<CattleShow> getCattleShows() {
		return this.cattleShows;
	}

	public void setCattleShows(Set<CattleShow> cattleShows) {
		this.cattleShows = cattleShows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<MedicineImport> getMedicineImports() {
		return this.medicineImports;
	}

	public void setMedicineImports(Set<MedicineImport> medicineImports) {
		this.medicineImports = medicineImports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<ToolRelease> getToolReleases() {
		return this.toolReleases;
	}

	public void setToolReleases(Set<ToolRelease> toolReleases) {
		this.toolReleases = toolReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Alert> getAlerts() {
		return this.alerts;
	}

	public void setAlerts(Set<Alert> alerts) {
		this.alerts = alerts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<MedicineRelease> getMedicineReleases() {
		return this.medicineReleases;
	}

	public void setMedicineReleases(Set<MedicineRelease> medicineReleases) {
		this.medicineReleases = medicineReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<RawMaterialImport> getRawMaterialImports() {
		return this.rawMaterialImports;
	}

	public void setRawMaterialImports(Set<RawMaterialImport> rawMaterialImports) {
		this.rawMaterialImports = rawMaterialImports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<CattleStrain> getCattleStrains() {
		return this.cattleStrains;
	}

	public void setCattleStrains(Set<CattleStrain> cattleStrains) {
		this.cattleStrains = cattleStrains;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<RawMaterialOrder> getRawMaterialOrders() {
		return this.rawMaterialOrders;
	}

	public void setRawMaterialOrders(Set<RawMaterialOrder> rawMaterialOrders) {
		this.rawMaterialOrders = rawMaterialOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<ToolOrder> getToolOrders() {
		return this.toolOrders;
	}

	public void setToolOrders(Set<ToolOrder> toolOrders) {
		this.toolOrders = toolOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(Set<Disease> diseases) {
		this.diseases = diseases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<FormulaRecord2> getFormulaRecord2s() {
		return this.formulaRecord2s;
	}

	public void setFormulaRecord2s(Set<FormulaRecord2> formulaRecord2s) {
		this.formulaRecord2s = formulaRecord2s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<MedicineOrder> getMedicineOrders() {
		return this.medicineOrders;
	}

	public void setMedicineOrders(Set<MedicineOrder> medicineOrders) {
		this.medicineOrders = medicineOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Pregnant> getPregnants() {
		return this.pregnants;
	}

	public void setPregnants(Set<Pregnant> pregnants) {
		this.pregnants = pregnants;
	}

}
