package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pay generated by hbm2java
 */
@Entity
@Table(name = "pay")
public class Pay implements java.io.Serializable {

	private Integer id;
	private Worktogether worktogether;
	private Float processingfee;
	private String signsauction;

	public Pay() {
	}

	public Pay(Worktogether worktogether, Float processingfee, String signsauction) {
		this.worktogether = worktogether;
		this.processingfee = processingfee;
		this.signsauction = signsauction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "worktogether_id")
	public Worktogether getWorktogether() {
		return this.worktogether;
	}

	public void setWorktogether(Worktogether worktogether) {
		this.worktogether = worktogether;
	}

	@Column(name = "processingfee", precision = 12, scale = 0)
	public Float getProcessingfee() {
		return this.processingfee;
	}

	public void setProcessingfee(Float processingfee) {
		this.processingfee = processingfee;
	}

	@Column(name = "signsauction", length = 50)
	public String getSignsauction() {
		return this.signsauction;
	}

	public void setSignsauction(String signsauction) {
		this.signsauction = signsauction;
	}

}
