package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pregnant generated by hbm2java
 */
@Entity
@Table(name = "pregnant")
public class Pregnant implements java.io.Serializable {

	private Integer id;
	private Breeding breeding;
	private Member member;
	private StatusPregnant statusPregnant;
	private String datePreg;
	private String dateSchedule;
	private String timePreg;
	private String note;
	private String cattle;
	private Integer stat;
	/*private Integer cattlemaId;*/

	public Pregnant() {
	}

	public Pregnant(Breeding breeding, Member member, StatusPregnant statusPregnant, String datePreg, String dateSchedule,
			String timePreg, String note, String cattle, Integer stat/*, Integer cattlemaId*/) {
		this.breeding = breeding;
		this.member = member;
		this.statusPregnant = statusPregnant;
		this.datePreg = datePreg;
		this.dateSchedule = dateSchedule;
		this.timePreg = timePreg;
		this.note = note;
		this.cattle = cattle;
		this.stat = stat;
		/*this.cattlemaId = cattlemaId;*/
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "breeding_id")
	public Breeding getBreeding() {
		return this.breeding;
	}

	public void setBreeding(Breeding breeding) {
		this.breeding = breeding;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_pregnant_id")
	public StatusPregnant getStatusPregnant() {
		return this.statusPregnant;
	}

	public void setStatusPregnant(StatusPregnant statusPregnant) {
		this.statusPregnant = statusPregnant;
	}

	@Column(name = "date_preg", length = 10)
	public String getDatePreg() {
		return this.datePreg;
	}

	public void setDatePreg(String datePreg) {
		this.datePreg = datePreg;
	}

	@Column(name = "date_schedule", length = 19)
	public String getDateSchedule() {
		return this.dateSchedule;
	}

	public void setDateSchedule(String dateSchedule) {
		this.dateSchedule = dateSchedule;
	}

	@Column(name = "time_preg", length = 8)
	public String getTimePreg() {
		return this.timePreg;
	}

	public void setTimePreg(String timePreg) {
		this.timePreg = timePreg;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "cattle", length = 50)
	public String getCattle() {
		return this.cattle;
	}

	public void setCattle(String cattle) {
		this.cattle = cattle;
	}

	@Column(name = "stat")
	public Integer getStat() {
		return this.stat;
	}

	public void setStat(Integer stat) {
		this.stat = stat;
	}
	
	/*@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "cattlemaId")
	public Integer getCattlemaId() {
		return this.cattlemaId;
	}

	public void setCattlemaId(Integer cattlemaId) {
		this.cattlemaId = cattlemaId;
	}*/

}
