package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

/**
 * RawMaterialNutrient generated by hbm2java
 */
@Entity
@Table(name = "raw_material_nutrient")
public class RawMaterialNutrient implements java.io.Serializable {

	@Expose private Integer id;
	private RawMaterial rawMaterial;
	private UnitNutrient unitNutrient;
	private Date date;
	@Expose private Float protein;
	@Expose private Float tdn;
	@Expose private Float nfc;
	@Expose private Float dm;
	@Expose private Float uip;
	@Expose private Float dip;
	@Expose private Float ca;
	@Expose private Float p;
	@Expose private Float urea;
	@Expose private Float cl;
	@Expose private Float k;
	@Expose private Float s;
	@Expose private Float mg;
	@Expose private Float zn;
	@Expose private Float cu;
	@Expose private Float mn;
	@Expose private Float co;
	@Expose private Float se;
	@Expose private Float i;
	@Expose private Float vitA;
	@Expose private Float vitD;
	@Expose private Float vitE;
	@Expose private Float nel;
	@Expose private Float nem;
	@Expose private Float neg;
	@Expose private Float ndf;
	@Expose private Float ee;
	@Expose private Float cp;
	@Expose private Float cf;
	@Expose private Float ash;
	@Expose private Float nfe;
	@Expose private Float adf;
	@Expose private Float adl;
	@Expose private Float de;
	@Expose private Float me;
	@Expose private Float na;
	@Expose private Float fe;

	public RawMaterialNutrient() {
	}

	public RawMaterialNutrient(RawMaterial rawMaterial, UnitNutrient unitNutrient, Date date, Float protein, Float tdn,
			Float nfc, Float dm, Float uip, Float dip, Float ca, Float p, Float urea, Float cl, Float k, Float s,
			Float mg, Float zn, Float cu, Float mn, Float co, Float se, Float i, Float vitA, Float vitD, Float vitE,
			Float nel, Float nem, Float neg, Float ndf, Float ee, Float cp, Float cf, Float ash, Float nfe, Float adf,
			Float adl, Float de, Float me, Float na, Float fe) {
		this.rawMaterial = rawMaterial;
		this.unitNutrient = unitNutrient;
		this.date = date;
		this.protein = protein;
		this.tdn = tdn;
		this.nfc = nfc;
		this.dm = dm;
		this.uip = uip;
		this.dip = dip;
		this.ca = ca;
		this.p = p;
		this.urea = urea;
		this.cl = cl;
		this.k = k;
		this.s = s;
		this.mg = mg;
		this.zn = zn;
		this.cu = cu;
		this.mn = mn;
		this.co = co;
		this.se = se;
		this.i = i;
		this.vitA = vitA;
		this.vitD = vitD;
		this.vitE = vitE;
		this.nel = nel;
		this.nem = nem;
		this.neg = neg;
		this.ndf = ndf;
		this.ee = ee;
		this.cp = cp;
		this.cf = cf;
		this.ash = ash;
		this.nfe = nfe;
		this.adf = adf;
		this.adl = adl;
		this.de = de;
		this.me = me;
		this.na = na;
		this.fe = fe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Raw_material_id")
	public RawMaterial getRawMaterial() {
		return this.rawMaterial;
	}

	public void setRawMaterial(RawMaterial rawMaterial) {
		this.rawMaterial = rawMaterial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Unit_nutrient_id")
	public UnitNutrient getUnitNutrient() {
		return this.unitNutrient;
	}

	public void setUnitNutrient(UnitNutrient unitNutrient) {
		this.unitNutrient = unitNutrient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Protein", precision = 12, scale = 0)
	public Float getProtein() {
		return this.protein;
	}

	public void setProtein(Float protein) {
		this.protein = protein;
	}

	@Column(name = "TDN", precision = 12, scale = 0)
	public Float getTdn() {
		return this.tdn;
	}

	public void setTdn(Float tdn) {
		this.tdn = tdn;
	}

	@Column(name = "NFC", precision = 12, scale = 0)
	public Float getNfc() {
		return this.nfc;
	}

	public void setNfc(Float nfc) {
		this.nfc = nfc;
	}

	@Column(name = "DM", precision = 12, scale = 0)
	public Float getDm() {
		return this.dm;
	}

	public void setDm(Float dm) {
		this.dm = dm;
	}

	@Column(name = "UIP", precision = 12, scale = 0)
	public Float getUip() {
		return this.uip;
	}

	public void setUip(Float uip) {
		this.uip = uip;
	}

	@Column(name = "DIP", precision = 12, scale = 0)
	public Float getDip() {
		return this.dip;
	}

	public void setDip(Float dip) {
		this.dip = dip;
	}

	@Column(name = "Ca", precision = 12, scale = 0)
	public Float getCa() {
		return this.ca;
	}

	public void setCa(Float ca) {
		this.ca = ca;
	}

	@Column(name = "P", precision = 12, scale = 0)
	public Float getP() {
		return this.p;
	}

	public void setP(Float p) {
		this.p = p;
	}

	@Column(name = "Urea", precision = 12, scale = 0)
	public Float getUrea() {
		return this.urea;
	}

	public void setUrea(Float urea) {
		this.urea = urea;
	}

	@Column(name = "Cl", precision = 12, scale = 0)
	public Float getCl() {
		return this.cl;
	}

	public void setCl(Float cl) {
		this.cl = cl;
	}

	@Column(name = "K", precision = 12, scale = 0)
	public Float getK() {
		return this.k;
	}

	public void setK(Float k) {
		this.k = k;
	}

	@Column(name = "S", precision = 12, scale = 0)
	public Float getS() {
		return this.s;
	}

	public void setS(Float s) {
		this.s = s;
	}

	@Column(name = "Mg", precision = 12, scale = 0)
	public Float getMg() {
		return this.mg;
	}

	public void setMg(Float mg) {
		this.mg = mg;
	}

	@Column(name = "Zn", precision = 12, scale = 0)
	public Float getZn() {
		return this.zn;
	}

	public void setZn(Float zn) {
		this.zn = zn;
	}

	@Column(name = "Cu", precision = 12, scale = 0)
	public Float getCu() {
		return this.cu;
	}

	public void setCu(Float cu) {
		this.cu = cu;
	}

	@Column(name = "Mn", precision = 12, scale = 0)
	public Float getMn() {
		return this.mn;
	}

	public void setMn(Float mn) {
		this.mn = mn;
	}

	@Column(name = "Co", precision = 12, scale = 0)
	public Float getCo() {
		return this.co;
	}

	public void setCo(Float co) {
		this.co = co;
	}

	@Column(name = "Se", precision = 12, scale = 0)
	public Float getSe() {
		return this.se;
	}

	public void setSe(Float se) {
		this.se = se;
	}

	@Column(name = "I", precision = 12, scale = 0)
	public Float getI() {
		return this.i;
	}

	public void setI(Float i) {
		this.i = i;
	}

	@Column(name = "VitA", precision = 12, scale = 0)
	public Float getVitA() {
		return this.vitA;
	}

	public void setVitA(Float vitA) {
		this.vitA = vitA;
	}

	@Column(name = "VitD", precision = 12, scale = 0)
	public Float getVitD() {
		return this.vitD;
	}

	public void setVitD(Float vitD) {
		this.vitD = vitD;
	}

	@Column(name = "VitE", precision = 12, scale = 0)
	public Float getVitE() {
		return this.vitE;
	}

	public void setVitE(Float vitE) {
		this.vitE = vitE;
	}

	@Column(name = "NEl", precision = 12, scale = 0)
	public Float getNel() {
		return this.nel;
	}

	public void setNel(Float nel) {
		this.nel = nel;
	}

	@Column(name = "NEm", precision = 12, scale = 0)
	public Float getNem() {
		return this.nem;
	}

	public void setNem(Float nem) {
		this.nem = nem;
	}

	@Column(name = "NEg", precision = 12, scale = 0)
	public Float getNeg() {
		return this.neg;
	}

	public void setNeg(Float neg) {
		this.neg = neg;
	}

	@Column(name = "NDF", precision = 12, scale = 0)
	public Float getNdf() {
		return this.ndf;
	}

	public void setNdf(Float ndf) {
		this.ndf = ndf;
	}

	@Column(name = "EE", precision = 12, scale = 0)
	public Float getEe() {
		return this.ee;
	}

	public void setEe(Float ee) {
		this.ee = ee;
	}

	@Column(name = "CP", precision = 12, scale = 0)
	public Float getCp() {
		return this.cp;
	}

	public void setCp(Float cp) {
		this.cp = cp;
	}

	@Column(name = "CF", precision = 12, scale = 0)
	public Float getCf() {
		return this.cf;
	}

	public void setCf(Float cf) {
		this.cf = cf;
	}

	@Column(name = "Ash", precision = 12, scale = 0)
	public Float getAsh() {
		return this.ash;
	}

	public void setAsh(Float ash) {
		this.ash = ash;
	}

	@Column(name = "NFE", precision = 12, scale = 0)
	public Float getNfe() {
		return this.nfe;
	}

	public void setNfe(Float nfe) {
		this.nfe = nfe;
	}

	@Column(name = "ADF", precision = 12, scale = 0)
	public Float getAdf() {
		return this.adf;
	}

	public void setAdf(Float adf) {
		this.adf = adf;
	}

	@Column(name = "ADL", precision = 12, scale = 0)
	public Float getAdl() {
		return this.adl;
	}

	public void setAdl(Float adl) {
		this.adl = adl;
	}

	@Column(name = "DE", precision = 12, scale = 0)
	public Float getDe() {
		return this.de;
	}

	public void setDe(Float de) {
		this.de = de;
	}

	@Column(name = "ME", precision = 12, scale = 0)
	public Float getMe() {
		return this.me;
	}

	public void setMe(Float me) {
		this.me = me;
	}

	@Column(name = "Na", precision = 12, scale = 0)
	public Float getNa() {
		return this.na;
	}

	public void setNa(Float na) {
		this.na = na;
	}

	@Column(name = "Fe", precision = 12, scale = 0)
	public Float getFe() {
		return this.fe;
	}

	public void setFe(Float fe) {
		this.fe = fe;
	}

}
