package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RawMaterialFormula generated by hbm2java
 */
@Entity
@Table(name = "raw_material_formula")
public class RawMaterialFormula implements java.io.Serializable {

	private Integer id;
	private FormulaRecord formulaRecord;
	private FormulaRecord2 formulaRecord2;
	private String name;
	private Float value;
	private Float price;
	private Float dm;
	private Float cp;
	private Float tdn;
	private Float ndf;
	private Float vita;
	private Float vite;

	public RawMaterialFormula() {
	}

	public RawMaterialFormula(FormulaRecord formulaRecord, FormulaRecord2 formulaRecord2, String name, Float value,
			Float price, Float dm, Float cp, Float tdn, Float ndf, Float vita, Float vite) {
		this.formulaRecord = formulaRecord;
		this.formulaRecord2 = formulaRecord2;
		this.name = name;
		this.value = value;
		this.price = price;
		this.dm = dm;
		this.cp = cp;
		this.tdn = tdn;
		this.ndf = ndf;
		this.vita = vita;
		this.vite = vite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Formula_record_id")
	public FormulaRecord getFormulaRecord() {
		return this.formulaRecord;
	}

	public void setFormulaRecord(FormulaRecord formulaRecord) {
		this.formulaRecord = formulaRecord;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Formula_record2_id")
	public FormulaRecord2 getFormulaRecord2() {
		return this.formulaRecord2;
	}

	public void setFormulaRecord2(FormulaRecord2 formulaRecord2) {
		this.formulaRecord2 = formulaRecord2;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", precision = 12, scale = 0)
	public Float getValue() {
		return this.value;
	}

	public void setValue(Float value) {
		this.value = value;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "dm", precision = 12, scale = 0)
	public Float getDm() {
		return this.dm;
	}

	public void setDm(Float dm) {
		this.dm = dm;
	}

	@Column(name = "cp", precision = 12, scale = 0)
	public Float getCp() {
		return this.cp;
	}

	public void setCp(Float cp) {
		this.cp = cp;
	}

	@Column(name = "tdn", precision = 12, scale = 0)
	public Float getTdn() {
		return this.tdn;
	}

	public void setTdn(Float tdn) {
		this.tdn = tdn;
	}

	@Column(name = "ndf", precision = 12, scale = 0)
	public Float getNdf() {
		return this.ndf;
	}

	public void setNdf(Float ndf) {
		this.ndf = ndf;
	}

	@Column(name = "vita", precision = 12, scale = 0)
	public Float getVita() {
		return this.vita;
	}

	public void setVita(Float vita) {
		this.vita = vita;
	}

	@Column(name = "vite", precision = 12, scale = 0)
	public Float getVite() {
		return this.vite;
	}

	public void setVite(Float vite) {
		this.vite = vite;
	}

}
