package farm3.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawMaterialRelease generated by hbm2java
 */
@Entity
@Table(name = "raw_material_release")
public class RawMaterialRelease implements java.io.Serializable {

	private Integer id;
	private Member member;
	private RawMaterial rawMaterial;
	private String day;
	private int quantity;
	private Integer billId;

	public RawMaterialRelease() {
	}

	public RawMaterialRelease(Member member, RawMaterial rawMaterial, String day, int quantity) {
		this.member = member;
		this.rawMaterial = rawMaterial;
		this.day = day;
		this.quantity = quantity;
	}

	public RawMaterialRelease(Member member, RawMaterial rawMaterial, String day, int quantity, Integer billId) {
		this.member = member;
		this.rawMaterial = rawMaterial;
		this.day = day;
		this.quantity = quantity;
		this.billId = billId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id", nullable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "raw_material_id", nullable = false)
	public RawMaterial getRawMaterial() {
		return this.rawMaterial;
	}

	public void setRawMaterial(RawMaterial rawMaterial) {
		this.rawMaterial = rawMaterial;
	}

	@Column(name = "day", nullable = false, length = 10)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "bill_id")
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

}
