package farm3.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RawMaterialImport generated by hbm2java
 */
@Entity
@Table(name = "raw_material_import")
public class RawMaterialImport implements java.io.Serializable {

	private Integer id;
	private Member member;
	private RawMaterial rawMaterial;
	private Integer lot;
	private Integer quantity;
	private Integer price;
	private String dayMfd;
	private String dayExp;
	private String importRaw;
	private String place;
	private Integer billId;
	private Integer beforeQuantity;
	private String day;
	private int status;

	public RawMaterialImport() {
	}

	public RawMaterialImport(int status) {
		this.status = status;
	}

	public RawMaterialImport(Member member, RawMaterial rawMaterial, Integer lot, Integer quantity, Integer price,
			String dayMfd, String dayExp, String importRaw, String place, Integer billId, Integer beforeQuantity, String day,
			int status) {
		this.member = member;
		this.rawMaterial = rawMaterial;
		this.lot = lot;
		this.quantity = quantity;
		this.price = price;
		this.dayMfd = dayMfd;
		this.dayExp = dayExp;
		this.importRaw = importRaw;
		this.place = place;
		this.billId = billId;
		this.beforeQuantity = beforeQuantity;
		this.day = day;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "raw_material_id")
	public RawMaterial getRawMaterial() {
		return this.rawMaterial;
	}

	public void setRawMaterial(RawMaterial rawMaterial) {
		this.rawMaterial = rawMaterial;
	}

	@Column(name = "lot")
	public Integer getLot() {
		return this.lot;
	}

	public void setLot(Integer lot) {
		this.lot = lot;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "day_mfd", length = 10)
	public String getDayMfd() {
		return this.dayMfd;
	}

	public void setDayMfd(String dayMfd) {
		this.dayMfd = dayMfd;
	}

	@Column(name = "day_exp", length = 10)
	public String getDayExp() {
		return this.dayExp;
	}

	public void setDayExp(String dayExp) {
		this.dayExp = dayExp;
	}

	@Column(name = "import_raw", length = 200)
	public String getImportRaw() {
		return this.importRaw;
	}

	public void setImportRaw(String importRaw) {
		this.importRaw = importRaw;
	}

	@Column(name = "place", length = 100)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "bill_id")
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@Column(name = "before_quantity")
	public Integer getBeforeQuantity() {
		return this.beforeQuantity;
	}

	public void setBeforeQuantity(Integer beforeQuantity) {
		this.beforeQuantity = beforeQuantity;
	}

	@Column(name = "day", length = 10)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
