package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * Semen generated by hbm2java
 */
@Entity
@Table(name = "semen")
public class Semen implements java.io.Serializable {

	private Integer id;
	private Breed breed;
	private Bucket bucket;
	private Color color;
	private String nameCattle;
	private String HNumber;
	private String colorCattle;
	private String tubeColor;
	private String lidColor;
	private String tubeSize;
	private String farm;
	private String dealer;
	@Expose private int quantity;
	private Integer canister;
	private String rack;
	private int statusalert;
	private Set<Breeding> breedings = new HashSet<Breeding>(0);
	private Set<SemenRelease> semenReleases = new HashSet<SemenRelease>(0);
	private Set<SemenImport> semenImports = new HashSet<SemenImport>(0);
	private Set<SemenOrder> semenOrders = new HashSet<SemenOrder>(0);

	public Semen() {
	}

	public Semen(int quantity, int statusalert) {
		this.quantity = quantity;
		this.statusalert = statusalert;
	}

	public Semen(Breed breed, Bucket bucket, Color color, String nameCattle, String HNumber, String colorCattle,
			String tubeColor, String lidColor, String tubeSize, String farm, String dealer, int quantity,
			Integer canister, String rack, int statusalert, Set<Breeding> breedings, Set<SemenRelease> semenReleases,
			Set<SemenImport> semenImports, Set<SemenOrder> semenOrders) {
		this.breed = breed;
		this.bucket = bucket;
		this.color = color;
		this.nameCattle = nameCattle;
		this.HNumber = HNumber;
		this.colorCattle = colorCattle;
		this.tubeColor = tubeColor;
		this.lidColor = lidColor;
		this.tubeSize = tubeSize;
		this.farm = farm;
		this.dealer = dealer;
		this.quantity = quantity;
		this.canister = canister;
		this.rack = rack;
		this.statusalert = statusalert;
		this.breedings = breedings;
		this.semenReleases = semenReleases;
		this.semenImports = semenImports;
		this.semenOrders = semenOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "breed_id")
	public Breed getBreed() {
		return this.breed;
	}

	public void setBreed(Breed breed) {
		this.breed = breed;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bucket_id")
	public Bucket getBucket() {
		return this.bucket;
	}

	public void setBucket(Bucket bucket) {
		this.bucket = bucket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "color_id")
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@Column(name = "name_cattle", length = 200)
	public String getNameCattle() {
		return this.nameCattle;
	}

	public void setNameCattle(String nameCattle) {
		this.nameCattle = nameCattle;
	}

	@Column(name = "h_number", length = 45)
	public String getHNumber() {
		return this.HNumber;
	}

	public void setHNumber(String HNumber) {
		this.HNumber = HNumber;
	}

	@Column(name = "color_cattle", length = 45)
	public String getColorCattle() {
		return this.colorCattle;
	}

	public void setColorCattle(String colorCattle) {
		this.colorCattle = colorCattle;
	}

	@Column(name = "tube_color", length = 20)
	public String getTubeColor() {
		return this.tubeColor;
	}

	public void setTubeColor(String tubeColor) {
		this.tubeColor = tubeColor;
	}

	@Column(name = "lid_color", length = 20)
	public String getLidColor() {
		return this.lidColor;
	}

	public void setLidColor(String lidColor) {
		this.lidColor = lidColor;
	}

	@Column(name = "tube_size", length = 10)
	public String getTubeSize() {
		return this.tubeSize;
	}

	public void setTubeSize(String tubeSize) {
		this.tubeSize = tubeSize;
	}

	@Column(name = "farm", length = 45)
	public String getFarm() {
		return this.farm;
	}

	public void setFarm(String farm) {
		this.farm = farm;
	}

	@Column(name = "dealer", length = 45)
	public String getDealer() {
		return this.dealer;
	}

	public void setDealer(String dealer) {
		this.dealer = dealer;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "canister")
	public Integer getCanister() {
		return this.canister;
	}

	public void setCanister(Integer canister) {
		this.canister = canister;
	}

	@Column(name = "rack", length = 10)
	public String getRack() {
		return this.rack;
	}

	public void setRack(String rack) {
		this.rack = rack;
	}

	@Column(name = "statusalert", nullable = false)
	public int getStatusalert() {
		return this.statusalert;
	}

	public void setStatusalert(int statusalert) {
		this.statusalert = statusalert;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semen")
	public Set<Breeding> getBreedings() {
		return this.breedings;
	}

	public void setBreedings(Set<Breeding> breedings) {
		this.breedings = breedings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semen")
	public Set<SemenRelease> getSemenReleases() {
		return this.semenReleases;
	}

	public void setSemenReleases(Set<SemenRelease> semenReleases) {
		this.semenReleases = semenReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semen")
	public Set<SemenImport> getSemenImports() {
		return this.semenImports;
	}

	public void setSemenImports(Set<SemenImport> semenImports) {
		this.semenImports = semenImports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semen")
	public Set<SemenOrder> getSemenOrders() {
		return this.semenOrders;
	}

	public void setSemenOrders(Set<SemenOrder> semenOrders) {
		this.semenOrders = semenOrders;
	}

}
