package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusTreat generated by hbm2java
 */
@Entity
@Table(name = "status_treat")
public class StatusTreat implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<TreatmentHistory> treatmentHistories = new HashSet<TreatmentHistory>(0);
	private Set<Cattle> cattles = new HashSet<Cattle>(0);
	private Set<MedicineHealth> medicineHealth = new HashSet<MedicineHealth>(0);

	

	public StatusTreat() {
	}

	public StatusTreat(String value, Set<TreatmentHistory> treatmentHistories, Set<Cattle> cattles, Set<MedicineHealth> medicineHealth) {
		this.value = value;
		this.treatmentHistories = treatmentHistories;
		this.cattles = cattles;
		this.medicineHealth = medicineHealth;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusTreat")
	public Set<TreatmentHistory> getTreatmentHistories() {
		return this.treatmentHistories;
	}

	public void setTreatmentHistories(Set<TreatmentHistory> treatmentHistories) {
		this.treatmentHistories = treatmentHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusTreat")
	public Set<Cattle> getCattles() {
		return this.cattles;
	}

	public void setCattles(Set<Cattle> cattles) {
		this.cattles = cattles;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusTreat")
	public Set<MedicineHealth> getMedicineHealth() {
		return this.medicineHealth;
	}

	public void setMedicineHealth(Set<MedicineHealth> medicineHealth) {
		this.medicineHealth = medicineHealth;
	}

}
