package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status")
public class Status implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<ToolBroken> toolBrokens = new HashSet<ToolBroken>(0);
	private Set<ToolBorrow> toolBorrows = new HashSet<ToolBorrow>(0);

	public Status() {
	}

	public Status(String value) {
		this.value = value;
	}

	public Status(String value, Set<ToolBroken> toolBrokens, Set<ToolBorrow> toolBorrows) {
		this.value = value;
		this.toolBrokens = toolBrokens;
		this.toolBorrows = toolBorrows;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", nullable = false, length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<ToolBroken> getToolBrokens() {
		return this.toolBrokens;
	}

	public void setToolBrokens(Set<ToolBroken> toolBrokens) {
		this.toolBrokens = toolBrokens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<ToolBorrow> getToolBorrows() {
		return this.toolBorrows;
	}

	public void setToolBorrows(Set<ToolBorrow> toolBorrows) {
		this.toolBorrows = toolBorrows;
	}

}
