package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Synchronize generated by hbm2java
 */
@Entity
@Table(name = "synchronize")
public class Synchronize implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private Member member;
	private TypeSync typeSync;
	private String dateSync;

	public Synchronize() {
	}

	public Synchronize(Cattle cattle, Member member, TypeSync typeSync, String dateSync) {
		this.cattle = cattle;
		this.member = member;
		this.typeSync = typeSync;
		this.dateSync = dateSync;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_sync_id")
	public TypeSync getTypeSync() {
		return this.typeSync;
	}

	public void setTypeSync(TypeSync typeSync) {
		this.typeSync = typeSync;
	}

	@Column(name = "date_sync", length = 10)
	public String getDateSync() {
		return this.dateSync;
	}

	public void setDateSync(String dateSync) {
		this.dateSync = dateSync;
	}

}
