package farm3.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ToolBroken generated by hbm2java
 */
@Entity
@Table(name = "tool_broken")
public class ToolBroken implements java.io.Serializable {

	private Integer id;
	private Bill bill;
	private Member member;
	private Status status;
	private Tool tool;
	private Integer quantity;
	private String dayBroken;
	private String dayReturn;

	public ToolBroken() {
	}

	public ToolBroken(Bill bill, Member member, Status status, Tool tool, Integer quantity, String dayBroken,
			String dayReturn) {
		this.bill = bill;
		this.member = member;
		this.status = status;
		this.tool = tool;
		this.quantity = quantity;
		this.dayBroken = dayBroken;
		this.dayReturn = dayReturn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bill_id")
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tool_id")
	public Tool getTool() {
		return this.tool;
	}

	public void setTool(Tool tool) {
		this.tool = tool;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "day_broken", length = 10)
	public String getDayBroken() {
		return this.dayBroken;
	}

	public void setDayBroken(String dayBroken) {
		this.dayBroken = dayBroken;
	}

	@Column(name = "day_return", length = 10)
	public String getDayReturn() {
		return this.dayReturn;
	}

	public void setDayReturn(String dayReturn) {
		this.dayReturn = dayReturn;
	}

}
