package farm3.spring.model;
// Generated Sep 18, 2016 10:00:53 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ToolBorrow generated by hbm2java
 */
@Entity
@Table(name = "tool_borrow")
public class ToolBorrow implements java.io.Serializable {

	private Integer id;
	private Member member;
	private Status status;
	private Tool tool;
	private Integer quantity;
	private String dayBorrow;
	private String dayReturn;
	private Integer billId;

	public ToolBorrow() {
	}

	public ToolBorrow(Member member, Status status, Tool tool, Integer quantity, String dayBorrow, String dayReturn,
			Integer billId) {
		this.member = member;
		this.status = status;
		this.tool = tool;
		this.quantity = quantity;
		this.dayBorrow = dayBorrow;
		this.dayReturn = dayReturn;
		this.billId = billId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tool_id")
	public Tool getTool() {
		return this.tool;
	}

	public void setTool(Tool tool) {
		this.tool = tool;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "day_borrow", length = 10)
	public String getDayBorrow() {
		return this.dayBorrow;
	}

	public void setDayBorrow(String dayBorrow) {
		this.dayBorrow = dayBorrow;
	}

	@Column(name = "day_return", length = 10)
	public String getDayReturn() {
		return this.dayReturn;
	}

	public void setDayReturn(String dayReturn) {
		this.dayReturn = dayReturn;
	}

	@Column(name = "bill_id")
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

}
