package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * TreatmentHistory generated by hbm2java
 */
@Entity
@Table(name = "treatment_history")
public class TreatmentHistory implements java.io.Serializable {

	private Integer id;
	private Cattle cattle;
	private Disease disease;
	private Medicine medicine;
	private Member member;
	private StatusDisease statusDisease;
	private StatusMedicine statusMedicine;
	private StatusTreat statusTreat;
	private String symptom;
	private String causeOfIllness;
	private String beAllergic;
	private String dateTreat;
	private String dateEndTreat;
	private Integer doseUsesage;
	private String dateStartMed;
	private String dateStopMed;
	private String note;
	private String dateTreatHorn;
	private String dateTreatNum;
	private String dateTreatBirth;
	private String dateEndTreatHorn;
	private String dateEndTreatNum;
	private String dateEndTreatBirth;
	private TypeHealth typeHealth;
	private String timeTreat;

	public TreatmentHistory() {
	}

	public TreatmentHistory(Cattle cattle, Disease disease, Medicine medicine, Member member,
			StatusDisease statusDisease, StatusMedicine statusMedicine, StatusTreat statusTreat, String symptom,
			String causeOfIllness, String beAllergic, String dateTreat, String dateEndTreat, Integer doseUsesage,
			String dateStartMed, String dateStopMed, String note, String dateTreatHor, String dateTreatNum, String dateTreatBirth, String dateEndTreatHor, String dateEndTreatNum, String dateEndTreatBirth,
			TypeHealth typeHealth,String dateTreatHorn, String timeTreat) {
		this.cattle = cattle;
		this.disease = disease;
		this.medicine = medicine;
		this.member = member;
		this.statusDisease = statusDisease;
		this.statusMedicine = statusMedicine;
		this.statusTreat = statusTreat;
		this.symptom = symptom;
		this.causeOfIllness = causeOfIllness;
		this.beAllergic = beAllergic;
		this.dateTreat = dateTreat;
		this.dateEndTreat = dateEndTreat;
		this.doseUsesage = doseUsesage;
		this.dateStartMed = dateStartMed;
		this.dateStopMed = dateStopMed;
		this.note = note;
		this.dateTreatHorn = dateTreatHorn;
		this.dateTreatNum = dateTreatNum;
		this.dateTreatBirth = dateTreatBirth;
		this.dateEndTreat = dateEndTreat;
		this.dateEndTreatNum = dateEndTreatNum;
		this.dateEndTreatBirth = dateEndTreatBirth;
		this.typeHealth = typeHealth;
		this.timeTreat = timeTreat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_id")
	public Cattle getCattle() {
		return this.cattle;
	}

	public void setCattle(Cattle cattle) {
		this.cattle = cattle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disease_id")
	public Disease getDisease() {
		return this.disease;
	}

	public void setDisease(Disease disease) {
		this.disease = disease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicine_id")
	public Medicine getMedicine() {
		return this.medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member_id")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_disease")
	public StatusDisease getStatusDisease() {
		return this.statusDisease;
	}

	public void setStatusDisease(StatusDisease statusDisease) {
		this.statusDisease = statusDisease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_medicine")
	public StatusMedicine getStatusMedicine() {
		return this.statusMedicine;
	}

	public void setStatusMedicine(StatusMedicine statusMedicine) {
		this.statusMedicine = statusMedicine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_treat_id")
	public StatusTreat getStatusTreat() {
		return this.statusTreat;
	}

	public void setStatusTreat(StatusTreat statusTreat) {
		this.statusTreat = statusTreat;
	}

	@Column(name = "symptom", length = 400)
	public String getSymptom() {
		return this.symptom;
	}

	public void setSymptom(String symptom) {
		this.symptom = symptom;
	}

	@Column(name = "cause_of_illness", length = 400)
	public String getCauseOfIllness() {
		return this.causeOfIllness;
	}

	public void setCauseOfIllness(String causeOfIllness) {
		this.causeOfIllness = causeOfIllness;
	}

	@Column(name = "be_allergic", length = 400)
	public String getBeAllergic() {
		return this.beAllergic;
	}

	public void setBeAllergic(String beAllergic) {
		this.beAllergic = beAllergic;
	}

	@Column(name = "date_treat", length = 10)
	public String getDateTreat() {
		return this.dateTreat;
	}

	public void setDateTreat(String dateTreat) {
		this.dateTreat = dateTreat;
	}

	@Column(name = "date_end_treat", length = 10)
	public String getDateEndTreat() {
		return this.dateEndTreat;
	}

	public void setDateEndTreat(String dateEndTreat) {
		this.dateEndTreat = dateEndTreat;
	}

	@Column(name = "dose_usesage", length = 100)
	public Integer getDoseUsesage() {
		return this.doseUsesage;
	}

	public void setDoseUsesage(Integer doseUsesage) {
		this.doseUsesage = doseUsesage;
	}

	@Column(name = "date_start_med", length = 10)
	public String getDateStartMed() {
		return this.dateStartMed;
	}

	public void setDateStartMed(String dateStartMed) {
		this.dateStartMed = dateStartMed;
	}

	@Column(name = "date_stop_med", length = 10)
	public String getDateStopMed() {
		return this.dateStopMed;
	}

	public void setDateStopMed(String dateStopMed) {
		this.dateStopMed = dateStopMed;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "date_treat_horn")
	public String getDateTreatHorn() {
		return dateTreatHorn;
	}

	public void setDateTreatHorn(String dateTreatHorn) {
		this.dateTreatHorn = dateTreatHorn;
	}
	
	@Column(name = "date_treat_num")
	public String getDateTreatNum() {
		return dateTreatNum;
	}

	public void setDateTreatNum(String dateTreatNum) {
		this.dateTreatNum = dateTreatNum;
	}
	
	@Column(name = "date_treat_birth")
	public String getDateTreatBirth() {
		return dateTreatBirth;
	}

	public void setDateTreatBirth(String dateTreatBirth) {
		this.dateTreatBirth = dateTreatBirth;
	}

	@Column(name = "date_end_treat_horn")
	public String getDateEndTreatHorn() {
		return dateEndTreatHorn;
	}

	public void setDateEndTreatHorn(String dateEndTreatHorn) {
		this.dateEndTreatHorn = dateEndTreatHorn;
	}

	@Column(name = "date_end_treat_num")
	public String getDateEndTreatNum() {
		return dateEndTreatNum;
	}

	public void setDateEndTreatNum(String dateEndTreatNum) {
		this.dateEndTreatNum = dateEndTreatNum;
	}

	@Column(name = "date_end_treat_birth")
	public String getDateEndTreatBirth() {
		return dateEndTreatBirth;
	}

	public void setDateEndTreatBirth(String dateEndTreatBirth) {
		this.dateEndTreatBirth = dateEndTreatBirth;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_health_id")
	public TypeHealth getTypeHealth() {
		return this.typeHealth;
	}

	public void setTypeHealth(TypeHealth typeHealth) {
		this.typeHealth = typeHealth;
	}

	@Column(name = "time_treat")
	public String getTimeTreat() {
		return timeTreat;
	}

	public void setTimeTreat(String timeTreat) {
		this.timeTreat = timeTreat;
	}
	
	
}
