package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeBucket generated by hbm2java
 */
@Entity
@Table(name = "type_bucket")
public class TypeBucket implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<Bucket> buckets = new HashSet<Bucket>(0);

	public TypeBucket() {
	}

	public TypeBucket(String value, Set<Bucket> buckets) {
		this.value = value;
		this.buckets = buckets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeBucket")
	public Set<Bucket> getBuckets() {
		return this.buckets;
	}

	public void setBuckets(Set<Bucket> buckets) {
		this.buckets = buckets;
	}

}
