package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeHorn generated by hbm2java
 */
@Entity
@Table(name = "type_horn")
public class TypeHorn implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<HornDetering> hornDeterings = new HashSet<HornDetering>(0);

	public TypeHorn() {
	}

	public TypeHorn(String value, Set<HornDetering> hornDeterings) {
		this.value = value;
		this.hornDeterings = hornDeterings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeHorn")
	public Set<HornDetering> getHornDeterings() {
		return this.hornDeterings;
	}

	public void setHornDeterings(Set<HornDetering> hornDeterings) {
		this.hornDeterings = hornDeterings;
	}

}
