package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeFormula generated by hbm2java
 */
@Entity
@Table(name = "type_formula")
public class TypeFormula implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<FormulaRecord> formulaRecords = new HashSet<FormulaRecord>(0);
	private Set<FormulaRecord2> formulaRecord2s = new HashSet<FormulaRecord2>(0);

	public TypeFormula() {
	}

	public TypeFormula(String value) {
		this.value = value;
	}

	public TypeFormula(String value, Set<FormulaRecord> formulaRecords, Set<FormulaRecord2> formulaRecord2s) {
		this.value = value;
		this.formulaRecords = formulaRecords;
		this.formulaRecord2s = formulaRecord2s;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", nullable = false, length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeFormula")
	public Set<FormulaRecord> getFormulaRecords() {
		return this.formulaRecords;
	}

	public void setFormulaRecords(Set<FormulaRecord> formulaRecords) {
		this.formulaRecords = formulaRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeFormula")
	public Set<FormulaRecord2> getFormulaRecord2s() {
		return this.formulaRecord2s;
	}

	public void setFormulaRecord2s(Set<FormulaRecord2> formulaRecord2s) {
		this.formulaRecord2s = formulaRecord2s;
	}

}
