package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeNutrient generated by hbm2java
 */
@Entity
@Table(name = "type_nutrient")
public class TypeNutrient implements java.io.Serializable {

	private Integer id;
	private FormulaRecord formulaRecord;
	private String value;
	private Set<CattleNutrient> cattleNutrients = new HashSet<CattleNutrient>(0);
	private Set<Cattle> cattles = new HashSet<Cattle>(0);

	public TypeNutrient() {
	}

	public TypeNutrient(FormulaRecord formulaRecord, String value, Set<CattleNutrient> cattleNutrients,
			Set<Cattle> cattles) {
		this.formulaRecord = formulaRecord;
		this.value = value;
		this.cattleNutrients = cattleNutrients;
		this.cattles = cattles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Formula_record_id")
	public FormulaRecord getFormulaRecord() {
		return this.formulaRecord;
	}

	public void setFormulaRecord(FormulaRecord formulaRecord) {
		this.formulaRecord = formulaRecord;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeNutrient")
	public Set<CattleNutrient> getCattleNutrients() {
		return this.cattleNutrients;
	}

	public void setCattleNutrients(Set<CattleNutrient> cattleNutrients) {
		this.cattleNutrients = cattleNutrients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeNutrient")
	public Set<Cattle> getCattles() {
		return this.cattles;
	}

	public void setCattles(Set<Cattle> cattles) {
		this.cattles = cattles;
	}

}
