package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeCow generated by hbm2java
 */
@Entity
@Table(name = "type_health")
public class TypeHealth implements java.io.Serializable {

	private Integer id;
	private String value;

	private Set<TreatmentHistory> treatmentHistory = new HashSet<TreatmentHistory>(0);
	

	public TypeHealth() {
	}

	public TypeHealth(String value, Set<TreatmentHistory> treatmentHistory) {
		this.value = value;
		this.treatmentHistory = treatmentHistory;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeHealth")
	public Set<TreatmentHistory> getTreatmentHistory() {
		return this.treatmentHistory;
	}

	public void setTreatmentHistory(Set<TreatmentHistory> treatmentHistory) {
		this.treatmentHistory = treatmentHistory;
	}
	

}
