package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeTool generated by hbm2java
 */
@Entity
@Table(name = "type_tool")
public class TypeTool implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<Tool> tools = new HashSet<Tool>(0);

	public TypeTool() {
	}

	public TypeTool(String value, Set<Tool> tools) {
		this.value = value;
		this.tools = tools;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeTool")
	public Set<Tool> getTools() {
		return this.tools;
	}

	public void setTools(Set<Tool> tools) {
		this.tools = tools;
	}

}
