package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import farm3.spring.dao.TypeDairyDao;

/**
 * TypeCow generated by hbm2java
 */
@Entity
@Table(name = "type_dairy")
public class TypeDairy implements java.io.Serializable {

	private Integer id;
	private String value;
	
	private Set<Cattle> cattles = new HashSet<Cattle>(0);

	public TypeDairy() {
	}

	public TypeDairy(String value, Set<Cattle> cattles) {
		this.value = value;
		this.cattles = cattles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "value", unique = true, length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeDairy")
	public Set<Cattle> getCattles() {
		return this.cattles;
	}
	

	public void setCattles(Set<Cattle> cattles) {
		this.cattles = cattles;
	}


}
