package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.google.gson.annotations.Expose;

/**
 * UnitRawMaterial generated by hbm2java
 */
@Entity
@Table(name = "unit_raw_material")
public class UnitRawMaterial implements java.io.Serializable {

	private Integer id;
	@Expose private String value;
	private Set<RawMaterial> rawMaterials = new HashSet<RawMaterial>(0);

	public UnitRawMaterial() {
	}

	public UnitRawMaterial(String value, Set<RawMaterial> rawMaterials) {
		this.value = value;
		this.rawMaterials = rawMaterials;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", unique = true, length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitRawMaterial")
	public Set<RawMaterial> getRawMaterials() {
		return this.rawMaterials;
	}

	public void setRawMaterials(Set<RawMaterial> rawMaterials) {
		this.rawMaterials = rawMaterials;
	}

}
