package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnitNutrient generated by hbm2java
 */
@Entity
@Table(name = "unit_nutrient")
public class UnitNutrient implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<CattleNutrient> cattleNutrients = new HashSet<CattleNutrient>(0);
	private Set<RawMaterialNutrient> rawMaterialNutrients = new HashSet<RawMaterialNutrient>(0);

	public UnitNutrient() {
	}

	public UnitNutrient(String value, Set<CattleNutrient> cattleNutrients,
			Set<RawMaterialNutrient> rawMaterialNutrients) {
		this.value = value;
		this.cattleNutrients = cattleNutrients;
		this.rawMaterialNutrients = rawMaterialNutrients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "value", length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitNutrient")
	public Set<CattleNutrient> getCattleNutrients() {
		return this.cattleNutrients;
	}

	public void setCattleNutrients(Set<CattleNutrient> cattleNutrients) {
		this.cattleNutrients = cattleNutrients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitNutrient")
	public Set<RawMaterialNutrient> getRawMaterialNutrients() {
		return this.rawMaterialNutrients;
	}

	public void setRawMaterialNutrients(Set<RawMaterialNutrient> rawMaterialNutrients) {
		this.rawMaterialNutrients = rawMaterialNutrients;
	}

}
