package farm3.spring.model;
// Generated Sep 25, 2016 9:18:21 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Worktogether generated by hbm2java
 */
@Entity
@Table(name = "worktogether")
public class Worktogether implements java.io.Serializable {

	private Integer id;
	private Festivity festivity;
	private String name;
	private String surname;
	private String idcard;
	private String address;
	private Set<Pay> pays = new HashSet<Pay>(0);
	private Set<Report> reports = new HashSet<Report>(0);

	public Worktogether() {
	}

	public Worktogether(Festivity festivity, String name, String surname, String idcard, String address, Set<Pay> pays,
			Set<Report> reports) {
		this.festivity = festivity;
		this.name = name;
		this.surname = surname;
		this.idcard = idcard;
		this.address = address;
		this.pays = pays;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "festivity_id")
	public Festivity getFestivity() {
		return this.festivity;
	}

	public void setFestivity(Festivity festivity) {
		this.festivity = festivity;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", length = 50)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "idcard", length = 50)
	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "worktogether")
	public Set<Pay> getPays() {
		return this.pays;
	}

	public void setPays(Set<Pay> pays) {
		this.pays = pays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "worktogether")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

}
